In [1]:
import os
os.environ["HF_HOME"] = "/rds/general/user/rmw324/home/raels_playground/hugging_face_llms"

import gc, re
import numpy as np
import pandas as pd
import torch

import dllm
from dllm.core.samplers import MDLMSampler, MDLMSamplerConfig

print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.6.0+cu124 | cuda: True

In [2]:
DATA_DIR = "/rds/general/user/rmw324/home/raels_playground/datasets/pet_finder"

train = pd.read_csv(os.path.join(DATA_DIR, "train/train.csv"))
breed_labels = pd.read_csv(os.path.join(DATA_DIR, "BreedLabels.csv"))
color_labels = pd.read_csv(os.path.join(DATA_DIR, "ColorLabels.csv"))

breed_map = dict(zip(breed_labels["BreedID"], breed_labels["BreedName"]))
color_map = dict(zip(color_labels["ColorID"], color_labels["ColorName"]))

GENDER_MAP = {1: "Male", 2: "Female", 3: "Mixed"}
SIZE_MAP   = {1: "Small", 2: "Medium", 3: "Large", 4: "Extra Large"}
FUR_MAP    = {1: "Short", 2: "Medium", 3: "Long"}
YESNO_MAP  = {1: "Yes", 2: "No", 3: "Not Sure"}
HEALTH_MAP = {1: "Healthy", 2: "Minor Injury", 3: "Serious Injury"}
TYPE_MAP   = {1: "Dog", 2: "Cat"}

def to_readable(df):
    out = df.copy()
    out["Type"]         = out["Type"].map(TYPE_MAP)
    out["Gender"]       = out["Gender"].map(GENDER_MAP)
    out["MaturitySize"] = out["MaturitySize"].map(SIZE_MAP)
    out["FurLength"]    = out["FurLength"].map(FUR_MAP)
    out["Vaccinated"]   = out["Vaccinated"].map(YESNO_MAP)
    out["Dewormed"]     = out["Dewormed"].map(YESNO_MAP)
    out["Sterilized"]   = out["Sterilized"].map(YESNO_MAP)
    out["Health"]       = out["Health"].map(HEALTH_MAP)
    out["Breed1"]       = out["Breed1"].map(breed_map).fillna("Unknown")
    out["Color1"]       = out["Color1"].map(color_map).fillna("Unknown")
    return out

print(train.shape)
train.head(2)

(14993, 24)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0

In [3]:
CUE = re.compile(
    r"\b(he|she|him|her|his|hers|male|female|boy|girl|"
    r"black|white|brown|gray|grey|orange|yellow|tabby|cream|golden|"
    r"small|medium|large|tiny|huge|big|"
    r"short|long|fluffy|"
    r"vaccinated|sterilized|spayed|neutered|dewormed|kitten|puppy)\b",
    re.IGNORECASE,
)

mask = (
    train["Description"].notna()
    & (train["Description"].str.len() > 200)
    & train["Description"].str.contains(CUE, na=False, regex=True)
)
candidates = train[mask].head(25).reset_index(drop=True)
candidates_readable = to_readable(candidates)
print(f"Selected {len(candidates_readable)} rows")
candidates_readable[["Type","Name","Gender","Color1","MaturitySize","FurLength","Age"]].head()

/var/tmp/pbs.2661085.pbs-7/ipykernel_2542523/2402266899.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  & train["Description"].str.contains(CUE, na=False, regex=True)

Selected 25 rows

  Type    Name  Gender Color1 MaturitySize FurLength  Age
0  Cat  Nibble    Male  Black        Small     Short    3
1  Dog  Brisco    Male  Brown       Medium    Medium    1
2  Dog  Hunter    Male  Black       Medium     Short    1
3  Cat   BULAT    Male  Black       Medium      Long   12
4  Cat   Kitty  Female  Black       Medium    Medium   12

In [4]:
DISPLAY_FIELDS = ["Type","Name","Age","Breed1","Gender","Color1",
                  "MaturitySize","FurLength","Vaccinated","Sterilized",
                  "Health","Description"]

for i, row in candidates_readable.iterrows():
    print(f"\n=== Row {i} ===")
    for f in DISPLAY_FIELDS:
        val = str(row[f])
        if f == "Description" and len(val) > 500:
            val = val[:500] + "..."
        print(f"  {f}: {val}")

=== Row 0 ===
  Type: Cat
  Name: Nibble
  Age: 3
  Breed1: Tabby
  Gender: Male
  Color1: Black
  MaturitySize: Small
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: Nibble is a 3+ month old ball of cuteness. He is energetic and playful. I rescued a couple of cats a few months ago but could not get them neutered in time as the clinic was fully scheduled. The result was this little kitty. I do not have enough space and funds to care for more cats in my household. Looking for responsible people to take over Nibble's care.

=== Row 1 ===
  Type: Dog
  Name: Brisco
  Age: 1
  Breed1: Mixed Breed
  Gender: Male
  Color1: Brown
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: Yes
  Sterilized: No
  Health: Healthy
  Description: Their pregnant mother was dumped by her irresponsible owner at the roadside near some shops in Subang Jaya. Gave birth to them at the roadside. They are all healthy and adorable puppies. Already dewormed, vaccinated and ready to go to a home. No tying or caging for long hours as guard dogs. However, it is acceptable to cage or tie for precautionary purposes. Interested to adopt pls call me.

=== Row 2 ===
  Type: Dog
  Name: Hunter
  Age: 1
  Breed1: Mixed Breed
  Gender: Male
  Color1: Black
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: This handsome yet cute boy is up for adoption. He is the most playful pal we've seen in our puppies. He loves to nibble on shoelaces , Chase you at such a young age. Imagine what a cute brat he will be when he grows. We are looking for a loving home for Hunter , one that will take care of him and give him the love that he needs. Please call urgently if you would like to adopt this cutie.

=== Row 3 ===
  Type: Cat
  Name: BULAT
  Age: 12
  Breed1: Domestic Long Hair
  Gender: Male
  Color1: Black
  MaturitySize: Medium
  FurLength: Long
  Vaccinated: No
  Sterilized: Not Sure
  Health: Healthy
  Description: anyone within the area of ipoh or taiping who interested to adopt my cat can contact my father at this number (mazuvil)or can just email me. currently bulat is at my hometown at perak but anyone outside the area still want to adopt can travel there to my hometown.there is a lot of cats in my house rite now..i think i should let one of them go to a better owner who can give better attention to him.

=== Row 4 ===
  Type: Cat
  Name: Kitty
  Age: 12
  Breed1: Domestic Medium Hair
  Gender: Female
  Color1: Black
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: Not Sure
  Sterilized: Not Sure
  Health: Healthy
  Description: Very manja and gentle stray cat found, we would really like to find a home for it because we cannot keep her for ourselves for long. Has a very cute high pitch but soft meow. Please contact me if you would be interested in adopting.

=== Row 5 ===
  Type: Cat
  Name: Kali
  Age: 3
  Breed1: Domestic Long Hair
  Gender: Female
  Color1: Black
  MaturitySize: Large
  FurLength: Long
  Vaccinated: Yes
  Sterilized: No
  Health: Healthy
  Description: Kali is a super playful kitten who is on the go the minute she wakes up. She is very quiet and only meows very rarely. She likes to cuddle when she is sleepy and also when she wakes up from a nap. As long as she has her toys, she keeps herself active and busy during the day. Would recommend you spend at least half an hour every night to play with her as it is her normal routine now. Would recommend that you house her alone as a single cat or with another kitten. She has had her second vaccinatio...

=== Row 6 ===
  Type: Dog
  Name: Peanut
  Age: 2
  Breed1: Mixed Breed
  Gender: Male
  Color1: Brown
  MaturitySize: Medium
  FurLength: Long
  Vaccinated: Yes
  Sterilized: No
  Health: Healthy
  Description: Peanut was an abused puppy until he was rescued. He was very scared of people but now he is a very happy and active puppy! He is a really loving puppy now. (: Lester Jenny Will you adopt him? ================================================== Adopters are required to vaccinate and neuter them. ==================================================

=== Row 7 ===
  Type: Cat
  Name: 2 Mths Old Cute Kitties
  Age: 2
  Breed1: Domestic Medium Hair
  Gender: Mixed
  Color1: Black
  MaturitySize: Small
  FurLength: Medium
  Vaccinated: No
  Sterilized: Not Sure
  Health: Healthy
  Description: Hi Pet Lovers! This is my first posting and I need help! 3 months ago we befriended a mother stray cat with 3 kittens in our area and we 'adopted' them but they come and go as they please. 2 months ago the mother gave birth to a litter of 7 cute kittens and we have been taking care of the mother and the kittens ever since in our home...in the ground floor bathroom! Some of the kittens look half-persian with long hair,evident also from the earlier stray batch we adopted. Looking for good caring h...

=== Row 8 ===
  Type: Dog
  Name: Lost Dog
  Age: 3
  Breed1: Mixed Breed
  Gender: Female
  Color1: Brown
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: Not Sure
  Sterilized: Not Sure
  Health: Healthy
  Description: Lost Dog Found (Bandar Menjalara, Kepong／Taman Bukit Maluri or Desa Park City) 迷途犬被尋獲 (甲洞孟加拉惹／武吉馬魯里／Desa Park City) Area lost puppy found 小狗被發現地點：Bandar Sri Menjalara, Kepong, KL, Malaysia 大馬吉隆坡甲洞孟加拉惹 How the lost dog found 狗兒如何被發現: The lost puppy entered my staying place itself. 迷途小狗自行進我居住地。 Condition 情況: 雖好像幾天沒進食。看起來健康。頸上系有紅帶。目前甲洞孟加拉惹住宅區保安處看顧。Few days without food. Looks healthy. Neck tied with red belt. Currently taken care by security guard of housing area of Bandar Menjalara.

=== Row 9 ===
  Type: Dog
  Name: Max
  Age: 78
  Breed1: Terrier
  Gender: Male
  Color1: Black
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: Not Sure
  Sterilized: Not Sure
  Health: Healthy
  Description: We moved out of our apartment to a landed home and there were many friendly strays in the neighbourhood. My grandma's neighbour was moving homes and was looking for a home for their pet.I pleaded with my mom to let us adopt him and he's fun-loving, he plays football and is a great goalie yet a loyal guardog. Now we are moving abroad and Max has no home.

=== Row 10 ===
  Type: Dog
  Name: Blackie
  Age: 8
  Breed1: Mixed Breed
  Gender: Female
  Color1: Brown
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: No
  Sterilized: Yes
  Health: Healthy
  Description: shes active... she can obey wht command that u told her.. example shakeshand . sleep and eat .. command in english n tamil :).. she will bark if thr suspicius ppl... good for guard act like a male dog..she will sleept in mattres or cradle..whn she eat u can even touch her...we let her because no time to care she... so anyybody intrested to addopt plss call to.. im Mr.Tom..thx petfinder..

=== Row 11 ===
  Type: Dog
  Name: Beauty
  Age: 2
  Breed1: Mixed Breed
  Gender: Female
  Color1: Black
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: This cutie dumped by it's owner at the market and almost kill by the car, after kicking by the guy, trying to hide herself for safe under the car while the driver is ready to run, ran to her hit on the car to notice the driver stop before i pulled her out and safe her. Luckily the kindness factory guy is allowed me to keep her there, cause my shop is full with 19 dogs and cats, situation not allow me to take in more, due to my work i could only feed her once a day and clean her cage. She's a bla...

=== Row 12 ===
  Type: Cat
  Name: nan
  Age: 1
  Breed1: Domestic Short Hair
  Gender: Mixed
  Color1: Black
  MaturitySize: Small
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: Birth Date: Oct 30th Kitty 1, Melly -Female Sangat comel and vokal. Kitty 2, Tootsie - Male Badan putih, tapi ekor hitam and telinga kekuning-kuningan, macam kucing 3 color. Kitty 3, Bo -Male Corak badan 3 tompok, he is one of the most quite and lightest kitty of the litter tapi jantan. Kitty 4, Michii - Female Macam abang kembar, she is very subtle and sweet, have 1 big spot behind her back and 1 super cute spot belakang telinga. Kitty 5, Missy - Female. She is very curious and adventurous. Ver...

=== Row 13 ===
  Type: Dog
  Name: Godiva
  Age: 12
  Breed1: Mixed Breed
  Gender: Female
  Color1: Brown
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: No
  Sterilized: Yes
  Health: Healthy
  Description: Godiva was rescued in Serdang residential area. Her group of friends were caught by dog catcher team and she is the only one left. Being stray, she is not afraid of human touch, she is believed to be fed by some household throughout the period. Godiva looks gorgeous and her unigue colour coats is the eye - catcher. Medium length hair, she is absolutely beautiful and would be a good loving companion. Please do give her a good home.

=== Row 14 ===
  Type: Dog
  Name: Donut
  Age: 10
  Breed1: Mixed Breed
  Gender: Female
  Color1: Black
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: Yes
  Sterilized: Yes
  Health: Healthy
  Description: Donut is a friendly doggie and very domesticated. She will bark at strangers and will not run out of the house. Needs a cage as her sleeping bed, she likes to lie in there. Her former owner abandoned her after she had demodex. She is cured now. Vaccination and neutering fees to be borne by adopter. Please call if you can give her a home.

=== Row 15 ===
  Type: Cat
  Name: Cikenet
  Age: 3
  Breed1: Domestic Short Hair
  Gender: Male
  Color1: Brown
  MaturitySize: Small
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: hello cikenets fans, i just wanna inform that cikenet is not lost, i just found out that he is adopted by one of this apartment resident, he become an indoor cat now, he is in good hands and im happy for him..

=== Row 16 ===
  Type: Cat
  Name: Garfield
  Age: 36
  Breed1: Persian
  Gender: Male
  Color1: Golden
  MaturitySize: Large
  FurLength: Medium
  Vaccinated: Yes
  Sterilized: Yes
  Health: Healthy
  Description: Garfield is a very large cat. Needs daily grooming. He has been groomed short and deflea. Very good wt other cats. Calm cat. He is neutered, vaccinated and dewormed. Must be kept indoors. Needs grooming and brushing as his fur is very soft and thick. If you are interested to adopt Garfield, please give me a call or sent me an email. thank you.

=== Row 17 ===
  Type: Cat
  Name: Pepper
  Age: 1
  Breed1: Domestic Short Hair
  Gender: Female
  Color1: Brown
  MaturitySize: Small
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: This kitten found at the roadside. Stay there and keep meowing. Kitty like to follow human feet. When we stand still, kitty just lean on our feed and sit quietly. Only for indoor adoption. And the adopter must take the kitten to vaccination (start from 2 months old) and neuter (at 6 months old).

=== Row 18 ===
  Type: Dog
  Name: Benji & Kimi
  Age: 4
  Breed1: Shih Tzu
  Gender: Mixed
  Color1: Brown
  MaturitySize: Small
  FurLength: Medium
  Vaccinated: Yes
  Sterilized: Yes
  Health: Healthy
  Description: Benji and his sister Kimi are a handsome pair of shitzu cross. Both have cute shaggy face, with brown patches over their white body. Very manja and need lots of attention and love. Only as indoor pets and no caging.

=== Row 19 ===
  Type: Dog
  Name: BoiBoi
  Age: 24
  Breed1: Mixed Breed
  Gender: Male
  Color1: Cream
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: Yes
  Sterilized: No
  Health: Healthy
  Description: Boiboi is rescued by my daughter 2 years ago from outside her tuition place. He was sick and abandoned alone without the mother. Now he is very healthy, playful and gentle. He is not only playful but also toilet trained and well behave. I hope he can have new family with full of love and caring.

=== Row 20 ===
  Type: Cat
  Name: nan
  Age: 4
  Breed1: Domestic Short Hair
  Gender: Female
  Color1: Black
  MaturitySize: Small
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: Two gorgeous kittens have just lost their mummy, and are looking for a loving home. Already on solid food. Potential adopters must be willing to spay, vaccinate, and love them as indoor cats. They've been together since birth, so preference will be given to those willing to welcome both. Existing experience with cats is also a big plus.

=== Row 21 ===
  Type: Cat
  Name: Comel
  Age: 2
  Breed1: Domestic Medium Hair
  Gender: Female
  Color1: Brown
  MaturitySize: Small
  FurLength: Medium
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: si comel ini memerlukan seseorang yang boleh menyayangi n menjaganya. she is a lovely cat :) love to be with people :D perlu di adopt dengan segera kerana keadaan sekarang bahaya baginya untuk tinggal di sini.

=== Row 22 ===
  Type: Dog
  Name: WHISKY
  Age: 12
  Breed1: Mixed Breed
  Gender: Male
  Color1: Black
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: This is Whisky, rescued from the streets. He is looking for a loving home. He is very friendly and doesn't bark unnecessarily. Gets along quite well with another dog. Please contact me if you wish to adopt him. No caging up or tying up.

=== Row 23 ===
  Type: Cat
  Name: Angel
  Age: 2
  Breed1: Domestic Medium Hair
  Gender: Female
  Color1: White
  MaturitySize: Medium
  FurLength: Medium
  Vaccinated: No
  Sterilized: No
  Health: Healthy
  Description: We temporarily fostered Angel's mother and her three kittens after birth. Angel is born on the 11 March . She is 9 weeks old now. We are looking for a home for Angel. We are looking for working Malaysians or Malaysian families to adopt her. Angel was rather timid and shy when she was a younger kitten but we've seen her blossom in the last few weeks. She is really loving towards her siblings. Note : We put her up for adoption earlier but when the potential adopter failed to turn up, we decided to...

=== Row 24 ===
  Type: Dog
  Name: Jack
  Age: 5
  Breed1: Jack Russell Terrier
  Gender: Male
  Color1: White
  MaturitySize: Medium
  FurLength: Short
  Vaccinated: Yes
  Sterilized: Yes
  Health: Healthy
  Description: Jack is a Jack Russell crossed. He is very friendly, active, playful, and joyful. He has four short legs and a stubby tail.Still it will wags vigourously atwhat delights him.You should see how he & his age gang troop around our garden & terrace.

In [5]:
# Edit this dict after inspecting the rows above. Pick cells whose Description
# (or surrounding row context) plausibly cues the answer.
# Eligible columns: Gender, Color1, MaturitySize, FurLength, Vaccinated, Sterilized, Health, Age
manual_masks = {
    0:  ["Gender", "MaturitySize"],
    1:  ["Color1", "FurLength"],
    2:  ["Gender"],
    3:  ["MaturitySize", "Vaccinated"],
    4:  ["FurLength"],
    5:  ["Gender", "Age"],
    6:  ["Color1"],
    7:  ["MaturitySize"],
    8:  ["Gender", "FurLength"],
    9:  ["Color1"],
    10: ["Vaccinated"],
    11: ["MaturitySize"],
    12: ["Gender"],
    13: ["FurLength", "Color1"],
    14: ["Gender"],
    15: ["MaturitySize"],
    16: ["FurLength"],
    17: ["Color1"],
    18: ["Gender", "Vaccinated"],
    19: ["MaturitySize"],
    20: ["Gender"],
    21: ["Color1"],
    22: ["FurLength"],
    23: ["MaturitySize"],
    24: ["Gender"],
}

ELIGIBLE = {"Gender","Color1","MaturitySize","FurLength",
            "Vaccinated","Sterilized","Health","Age"}
for k, v in manual_masks.items():
    bad = set(v) - ELIGIBLE
    assert not bad, f"Row {k}: column(s) {bad} not eligible"
print(f"Total masked cells: {sum(len(v) for v in manual_masks.values())}")

Total masked cells: 32

In [6]:
RENDER_FIELDS = ["Type","Name","Age","Breed1","Gender","Color1",
                 "MaturitySize","FurLength","Vaccinated","Sterilized",
                 "Health","Description"]

def render_for_llada(rows_df, masks_by_row, tokenizer, max_desc_words=40):
    """Concatenate all rows into one text block. Masked cells are replaced
    by tokenizer.mask_token * n_tokens (sized to the original value).
    Returns (text, ordered_keys) — keys are (row_idx, col_name, original_value)
    in the same order their masks appear in the text."""
    mask_token = tokenizer.mask_token
    parts = []
    keys = []
    for i, row in rows_df.iterrows():
        parts.append(f"\n=== Row {i+1} ===\n")
        masked_cols = set(masks_by_row.get(i, []))
        for f in RENDER_FIELDS:
            val = str(row[f])
            if f == "Age":
                try: val = str(int(float(val)))
                except: pass
            if f == "Description":
                words = val.split()
                if len(words) > max_desc_words:
                    val = " ".join(words[:max_desc_words]) + "..."
            if f in masked_cols:
                n_tok = max(1, len(tokenizer.encode(val, add_special_tokens=False)))
                parts.append(f"{f}: {mask_token * n_tok}\n")
                keys.append((i, f, val))
            else:
                parts.append(f"{f}: {val}\n")
    return "".join(parts), keys

def find_mask_runs(input_ids, mask_id):
    """Return list of (start, end_exclusive) for each contiguous run of mask_id."""
    runs = []
    in_run = False
    s = 0
    for idx, t in enumerate(input_ids):
        if t == mask_id:
            if not in_run:
                s = idx; in_run = True
        else:
            if in_run:
                runs.append((s, idx)); in_run = False
    if in_run:
        runs.append((s, len(input_ids)))
    return runs

In [7]:
# --- LLaDA inference (whole-table infill in a single forward) ---
ll_model = dllm.utils.get_model(model_name_or_path="GSAI-ML/LLaDA-8B-Instruct").eval()
ll_tokenizer = dllm.utils.get_tokenizer(model_name_or_path="GSAI-ML/LLaDA-8B-Instruct")
sampler = MDLMSampler(model=ll_model, tokenizer=ll_tokenizer)

text, keys = render_for_llada(candidates_readable, manual_masks, ll_tokenizer, max_desc_words=40)
input_ids = ll_tokenizer.encode(text, add_special_tokens=True)
print(f"Input length: {len(input_ids)} tokens")

mask_id = ll_tokenizer.mask_token_id
runs = find_mask_runs(input_ids, mask_id)
assert len(runs) == len(keys), f"runs {len(runs)} != keys {len(keys)} — tokenization drift; lower max_desc_words"
n_mask_tokens = sum(end - start for start, end in runs)
print(f"Masked cells: {len(keys)}, mask tokens: {n_mask_tokens}")

cfg = MDLMSamplerConfig(steps=n_mask_tokens, block_size=None, return_dict=True)
out = sampler.infill([input_ids], cfg)
seq = out.sequences[0].tolist()

llada_preds = {}
for (start, end), (row_i, col, orig) in zip(runs, keys):
    pred = ll_tokenizer.decode(seq[start:end]).strip()
    llada_preds[(row_i, col)] = pred

print("\nSample LLaDA predictions:")
for (row_i, col), pred in list(llada_preds.items())[:8]:
    orig = next(o for (i, c, o) in keys if i == row_i and c == col)
    print(f"  Row {row_i} {col}: pred={pred!r}  orig={orig!r}")

del ll_model, sampler
torch.cuda.empty_cache()
gc.collect()

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

Input length: 3115 tokens
Masked cells: 32, mask tokens: 32

Sample LLaDA predictions:
  Row 0 Gender: pred='Male'  orig='Male'
  Row 0 MaturitySize: pred='Medium'  orig='Small'
  Row 1 Color1: pred='Black'  orig='Brown'
  Row 1 FurLength: pred='Short'  orig='Medium'
  Row 2 Gender: pred='Male'  orig='Male'
  Row 3 MaturitySize: pred='Large'  orig='Medium'
  Row 3 Vaccinated: pred='Yes'  orig='No'
  Row 4 FurLength: pred='Medium'  orig='Medium'

339

In [11]:
# --- Llama-3.1-8B-Instruct baseline (autoregressive blank-fill) ---
from transformers import AutoModelForCausalLM, AutoTokenizer

LLAMA = "meta-llama/Llama-3.1-8B-Instruct"
llama_tok = AutoTokenizer.from_pretrained(LLAMA)
llama = AutoModelForCausalLM.from_pretrained(LLAMA, torch_dtype=torch.bfloat16, device_map="cuda").eval()

def render_for_llama(rows_df, masks_by_row, max_desc_words=40):
    parts, blank_keys = [], []
    k = 1
    for i, row in rows_df.iterrows():
        parts.append(f"\n=== Row {i+1} ===\n")
        masked_cols = set(masks_by_row.get(i, []))
        for f in RENDER_FIELDS:
            val = str(row[f])
            if f == "Age":
                try: val = str(int(float(val)))
                except: pass
            if f == "Description":
                words = val.split()
                if len(words) > max_desc_words:
                    val = " ".join(words[:max_desc_words]) + "..."
            if f in masked_cols:
                parts.append(f"{f}: [BLANK_{k}]\n")
                blank_keys.append((i, f, val))
                k += 1
            else:
                parts.append(f"{f}: {val}\n")
    return "".join(parts), blank_keys

table_text, blank_keys = render_for_llama(candidates_readable, manual_masks)
prompt = (
    "You are filling in missing fields in rows from a pet adoption dataset. "
    "Each row's Description is intact and provides context. Blanks are labelled "
    "[BLANK_1], [BLANK_2], etc.\n\n"
    f"Table:\n{table_text}\n\n"
    f"Output exactly {len(blank_keys)} lines, one per blank, in this format:\n"
    "[BLANK_1]: <value>\n[BLANK_2]: <value>\n...\n"
    "Use only short answers like 'Male', 'Medium', 'Yes', 'Black', '24'. "
    "Do not include any explanation or other text."
)
messages = [{"role": "user", "content": prompt}]
inp = llama_tok.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt").to("cuda")
with torch.no_grad():
    gen = llama.generate(inp, max_new_tokens=12 * len(blank_keys), do_sample=False)
response = llama_tok.decode(gen[0, inp.shape[1]:], skip_special_tokens=True)

llama_preds = {}
pat = re.compile(r"\[BLANK_(\d+)\]\s*:\s*(.+)")
for line in response.splitlines():
    m = pat.search(line)
    if m:
        k = int(m.group(1))
        if 1 <= k <= len(blank_keys):
            row_i, col, _ = blank_keys[k - 1]
            llama_preds[(row_i, col)] = m.group(2).strip().rstrip(".,")
for (i, c, _) in blank_keys:
    llama_preds.setdefault((i, c), "")

print(f"Llama parsed {sum(1 for v in llama_preds.values() if v)}/{len(blank_keys)} blanks")

del llama, llama_tok
torch.cuda.empty_cache()
gc.collect()

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

Llama parsed 32/32 blanks

1024

In [14]:

from tabpfn import TabPFNClassifier, TabPFNRegressor

TABPFN_FEATURES = ["Type","Age","Breed1","Breed2","Gender","Color1","Color2","Color3",
                   "MaturitySize","FurLength","Vaccinated","Dewormed","Sterilized",
                   "Health","Quantity","Fee","State"]

DECODE_FOR_COL = {
    "Gender": GENDER_MAP, "MaturitySize": SIZE_MAP, "FurLength": FUR_MAP,
    "Vaccinated": YESNO_MAP, "Sterilized": YESNO_MAP, "Health": HEALTH_MAP,
    "Color1": color_map,
}

# Group masked cells by column
by_col = {}
for row_i, cols in manual_masks.items():
    for c in cols:
        by_col.setdefault(c, []).append(row_i)

fit_pool = train.sample(n=min(8000, len(train)), random_state=0).reset_index(drop=True)

tabpfn_preds = {}
for col, row_indices in by_col.items():
    feats = [c for c in TABPFN_FEATURES if c != col]
    X_train = fit_pool[feats].values
    y_train = fit_pool[col].values
    X_test  = candidates.iloc[row_indices][feats].values

    if col == "Age":
        m = TabPFNRegressor()
    else:
        m = TabPFNClassifier()
    m.fit(X_train, y_train)
    preds = m.predict(X_test)

    for i, row_i in enumerate(row_indices):
        p = preds[i]
        if col == "Age":
            tabpfn_preds[(row_i, col)] = str(int(round(float(p))))
        else:
            decoder = DECODE_FOR_COL.get(col, {})
            tabpfn_preds[(row_i, col)] = decoder.get(int(p), str(p))

print(f"TabPFN predictions: {len(tabpfn_preds)}")
for k, v in list(tabpfn_preds.items())[:8]:
    print(f"  {k}: {v!r}")

tabpfn-v2.6-classifier-v2.6_default.ckpt:   0%|          | 0.00/43.0M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

tabpfn-v2.6-regressor-v2.6_default.ckpt:   0%|          | 0.00/51.6M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

TabPFN predictions: 32
  (0, 'Gender'): 'Male'
  (2, 'Gender'): 'Female'
  (5, 'Gender'): 'Female'
  (8, 'Gender'): 'Female'
  (12, 'Gender'): 'Mixed'
  (14, 'Gender'): 'Female'
  (18, 'Gender'): 'Female'
  (20, 'Gender'): 'Mixed'

In [15]:
# --- Evaluation: accuracy for categorical, MAE for Age ---
def norm(s): return str(s).strip().lower().rstrip(".,")

# Ground truth (readable strings, original Age)
gt = {}
for row_i, cols in manual_masks.items():
    for c in cols:
        if c == "Age":
            gt[(row_i, c)] = str(int(float(candidates.loc[row_i, "Age"])))
        else:
            gt[(row_i, c)] = str(candidates_readable.loc[row_i, c])

models = {"LLaDA": llada_preds, "Llama": llama_preds, "TabPFN": tabpfn_preds}
all_cols = sorted({c for cols in manual_masks.values() for c in cols})

rows_out = {}
for name, preds in models.items():
    rows_out[name] = {}
    for c in all_cols:
        keys = [k for k in gt if k[1] == c]
        if c == "Age":
            errs = []
            for k in keys:
                try: errs.append(abs(float(preds.get(k, "")) - float(gt[k])))
                except: errs.append(np.nan)
            rows_out[name][c] = f"MAE={np.nanmean(errs):.1f}" if errs else "—"
        else:
            hits = sum(norm(preds.get(k, "")) == norm(gt[k]) for k in keys)
            rows_out[name][c] = f"{hits}/{len(keys)} ({hits/len(keys):.0%})" if keys else "—"

results_df = pd.DataFrame(rows_out).T[all_cols]
print("=== Results (per-field per-model) ===")
print(results_df.to_string())

print("\n=== Worked examples ===")
for k in list(gt.keys())[:6]:
    row_i, col = k
    print(f"\nRow {row_i+1}  {col}:  truth={gt[k]!r}")
    for name in models:
        print(f"    {name:6s} {models[name].get(k, '')!r}")

=== Results (per-field per-model) ===
             Age     Color1  FurLength     Gender MaturitySize Vaccinated
LLaDA    MAE=2.0  1/6 (17%)  2/6 (33%)  6/9 (67%)    3/7 (43%)  1/3 (33%)
Llama    MAE=2.0  2/6 (33%)   0/6 (0%)  6/9 (67%)    3/7 (43%)  1/3 (33%)
TabPFN  MAE=10.0  4/6 (67%)  2/6 (33%)  5/9 (56%)    4/7 (57%)  2/3 (67%)

=== Worked examples ===

Row 1  Gender:  truth='Male'
    LLaDA  'Male'
    Llama  'Male'
    TabPFN 'Male'

Row 1  MaturitySize:  truth='Small'
    LLaDA  'Medium'
    Llama  'Medium'
    TabPFN 'Medium'

Row 2  Color1:  truth='Brown'
    LLaDA  'Black'
    Llama  'Brown'
    TabPFN 'Brown'

Row 2  FurLength:  truth='Medium'
    LLaDA  'Short'
    Llama  'Short'
    TabPFN 'Short'

Row 3  Gender:  truth='Male'
    LLaDA  'Male'
    Llama  'Male'
    TabPFN 'Female'

Row 4  MaturitySize:  truth='Medium'
    LLaDA  'Large'
    Llama  'Medium'
    TabPFN 'Medium'